// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace LLO.BookingLib
{
    public partial class LuxyService
    {
        public LuxyService()
        {
            LuxyBookingSchedules = new HashSet<LuxyBookingSchedule>();
            LuxyDailyServiceTemplates = new HashSet<LuxyDailyServiceTemplate>();
        }

        public string ServiceCode { get; set; }
        public string ActionByUsername { get; set; }
        public int ProductId { get; set; }
        public string Description { get; set; }

        public virtual Product Product { get; set; }
        public virtual ICollection<LuxyBookingSchedule> LuxyBookingSchedules { get; set; }
        public virtual ICollection<LuxyDailyServiceTemplate> LuxyDailyServiceTemplates { get; set; }
    }
}