// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace LLO.BookingLib
{
    public partial class LuxyBookingSchedule
    {
        public int Id { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string ServiceCode { get; set; }
        public Guid BookingGuid { get; set; }
        public bool IsCompleted { get; set; }
        public string ActionByUsername { get; set; }
        public string RatingCode { get; set; }
        public string Feedback { get; set; }
        public int? TemplateId { get; set; }

        public virtual LuxyBooking BookingGu { get; set; }
        public virtual LuxyService ServiceCodeNavigation { get; set; }
        public virtual LuxyDailyServiceTemplate Template { get; set; }
    }
}