// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace LLO.BookingLib
{
    public partial class LuxyDailyServiceTemplate
    {
        public LuxyDailyServiceTemplate()
        {
            LuxyBookingSchedules = new HashSet<LuxyBookingSchedule>();
        }

        public int Id { get; set; }
        public string ServiceCode { get; set; }
        public bool Day1 { get; set; }
        public bool Day2 { get; set; }
        public bool Day3 { get; set; }
        public int TimeShot24 { get; set; }
        public int DurationMinutes { get; set; }
        public string RoomCode { get; set; }

        public virtual LuxyRoom RoomCodeNavigation { get; set; }
        public virtual LuxyService ServiceCodeNavigation { get; set; }
        public virtual ICollection<LuxyBookingSchedule> LuxyBookingSchedules { get; set; }
    }
}