// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace LLO.BookingLib
{
    public partial class LuxyBooking
    {
        public LuxyBooking()
        {
            LuxyBookingSchedules = new HashSet<LuxyBookingSchedule>();
        }

        public string Username { get; set; }
        public string RoomCode { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime StartDateTime { get; set; }
        public DateTime EndDateTime { get; set; }
        public bool? IsVoid { get; set; }
        public Guid BookingGuid { get; set; }
        public string RoomNo { get; set; }
        public string Floor { get; set; }
        public string RoomType { get; set; }
        public decimal Price { get; set; }
        public int ProductId { get; set; }
        public bool? IsOpen { get; set; }
        public bool IsShared { get; set; }

        public virtual LuxyRoom RoomCodeNavigation { get; set; }
        public virtual ICollection<LuxyBookingSchedule> LuxyBookingSchedules { get; set; }
    }
}