//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luxy_DailyServiceTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Luxy_DailyServiceTemplate()
        {
            this.Luxy_BookingSchedule = new HashSet<Luxy_BookingSchedule>();
        }
    
        public int Id { get; set; }
        public string ServiceCode { get; set; }
        public bool Day1 { get; set; }
        public bool Day2 { get; set; }
        public bool Day3 { get; set; }
        public int TimeShot24 { get; set; }
        public int DurationMinutes { get; set; }
        public string RoomCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Luxy_BookingSchedule> Luxy_BookingSchedule { get; set; }
        public virtual Luxy_Room Luxy_Room { get; set; }
        public virtual Luxy_Service Luxy_Service { get; set; }
    }
}
