//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luxy_Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Luxy_Booking()
        {
            this.Luxy_BookingSchedule = new HashSet<Luxy_BookingSchedule>();
        }
    
        public string Username { get; set; }
        public string RoomCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid BookingGuid { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public bool IsVoid { get; set; }
        public string RoomNo { get; set; }
        public string Floor { get; set; }
        public string RoomType { get; set; }
        public decimal Price { get; set; }
        public int ProductId { get; set; }
    
        public virtual Luxy_Room Luxy_Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Luxy_BookingSchedule> Luxy_BookingSchedule { get; set; }
    }
}
