//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class luxylovedbEntities : DbContext
    {
        public luxylovedbEntities()
            : base("name=luxylovedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Luxy_Booking> Luxy_Booking { get; set; }
        public virtual DbSet<Luxy_BookingSchedule> Luxy_BookingSchedule { get; set; }
        public virtual DbSet<Luxy_DailyServiceTemplate> Luxy_DailyServiceTemplate { get; set; }
        public virtual DbSet<Luxy_Room> Luxy_Room { get; set; }
        public virtual DbSet<Luxy_Service> Luxy_Service { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
    }
}
