//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luxy_Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Luxy_Room()
        {
            this.Luxy_Booking = new HashSet<Luxy_Booking>();
            this.Luxy_DailyServiceTemplate = new HashSet<Luxy_DailyServiceTemplate>();
        }
    
        public string RoomCode { get; set; }
        public string RoomType { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool IsActive { get; set; }
        public string Name { get; set; }
        public string Floor { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string RoomNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Luxy_Booking> Luxy_Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Luxy_DailyServiceTemplate> Luxy_DailyServiceTemplate { get; set; }
        public virtual Product Product { get; set; }
    }
}
