//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luxy_BookingSchedule
    {
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string ServiceCode { get; set; }
        public System.Guid BookingGuid { get; set; }
        public bool IsCompleted { get; set; }
        public string ActionByUsername { get; set; }
        public string RatingCode { get; set; }
        public string Feedback { get; set; }
        public Nullable<int> TemplateId { get; set; }
    
        public virtual Luxy_Booking Luxy_Booking { get; set; }
        public virtual Luxy_DailyServiceTemplate Luxy_DailyServiceTemplate { get; set; }
        public virtual Luxy_Service Luxy_Service { get; set; }
    }
}
