//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luxy_Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Luxy_Service()
        {
            this.Luxy_BookingSchedule = new HashSet<Luxy_BookingSchedule>();
            this.Luxy_DailyServiceTemplate = new HashSet<Luxy_DailyServiceTemplate>();
        }
    
        public string ServiceCode { get; set; }
        public string ActionByUsername { get; set; }
        public int ProductId { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Luxy_BookingSchedule> Luxy_BookingSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Luxy_DailyServiceTemplate> Luxy_DailyServiceTemplate { get; set; }
        public virtual Product Product { get; set; }
    }
}
